FROM renovate/renovate:22.9.0-slim@sha256:d6afef1304c324e8af324901240d38eeb7dab8fdb28ffdc23f62fefcfd34b9bf

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="renovate" \
    org.opencontainers.image.source="https://github.com/renovatebot/renovate" \
    org.opencontainers.image.url="https://github.com/renovatebot/renovate"

USER 1000
