FROM renovate/renovate:22.25.6-slim@sha256:b1c03e9f3e1ef495ca4be8818634d017348bb2685c7e4f6f28247dad09a72a77

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="renovate" \
    org.opencontainers.image.source="https://github.com/renovatebot/renovate" \
    org.opencontainers.image.url="https://github.com/renovatebot/renovate"

USER 1000
