FROM registry:2.8.3

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="distribution" \
    org.opencontainers.image.source="https://github.com/distribution/distribution" \
    org.opencontainers.image.url="https://distribution.github.io/distribution"
