FROM registry:2.8.3@sha256:e54fc7162fb357c4476ffc09b5b8656c9cd113015386f2393d430a7379419aa0

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="distribution" \
    org.opencontainers.image.source="https://github.com/distribution/distribution" \
    org.opencontainers.image.url="https://distribution.github.io/distribution"
