FROM registry:2.8.3@sha256:319881be2ee9e345d5837d15842a04268de6a139e23be42654fc7664fc6eaf52

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="distribution" \
    org.opencontainers.image.source="https://github.com/distribution/distribution" \
    org.opencontainers.image.url="https://distribution.github.io/distribution"
