FROM roundcube/roundcubemail:1.6.11-apache@sha256:1e810fcde651c1d3b6cc59554a7fc937fe691412603739e26f66195759d96016

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
  name="roundcube" \
  org.opencontainers.image.source="https://github.com/roundcube/roundcubemail" \
  org.opencontainers.image.url="https://roundcube.net"

