FROM roundcube/roundcubemail:1.6.15-apache@sha256:f001e93ffa718bc1ed75eca8c853903e358a605b3f1228570468ca1e8646c666

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
  name="roundcube" \
  org.opencontainers.image.source="https://github.com/roundcube/roundcubemail" \
  org.opencontainers.image.url="https://roundcube.net"

