FROM roundcube/roundcubemail:1.6.9-apache@sha256:fd4e38790eda741680b7578cefe35dd5d2cfc9808e78c79addd7957c20882799

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
  name="roundcube" \
  org.opencontainers.image.source="https://github.com/roundcube/roundcubemail" \
  org.opencontainers.image.url="https://roundcube.net"

