trigger:
  batch: true
  branches:
    include:
      - "master"
pr:
  autoCancel: true
  branches:
    include:
      - "*"

variables:
  DOCKER_BUILDKIT: 1
  CI: true

jobs:
  - job: build_dotnet
    displayName: Build dotnet
    pool:
      vmImage: "ubuntu-16.04"
    strategy:
      matrix:
        aspnet:
          imageName: "dotnet-aspnet"
        sdk:
          imageName: "dotnet-sdk"
    steps:
      - template: .azure/build.yml
      - template: .azure/test-dotnet.yml
