trigger:
  batch: true
  branches:
    include:
      - "master"
      - "staging"
      - "trying"
pr:
  autoCancel: true
  branches:
    include:
      - "*"

variables:
  DOCKER_BUILDKIT: 1
  CI: true

jobs:
  - job: build_dotnet
    displayName: Build dotnet
    timeoutInMinutes: 10
    pool:
      vmImage: "ubuntu-16.04"
    strategy:
      matrix:
        aspnet:
          imageName: "dotnet-aspnet"
        sdk:
          imageName: "dotnet-sdk"
    steps:
      - template: .azure/build.yml
      - template: .azure/test-dotnet.yml

  - job: publish_dotnet
    displayName: Publish dotnet
    timeoutInMinutes: 10
    dependsOn: build_dotnet
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      vmImage: "ubuntu-16.04"
    strategy:
      matrix:
        aspnet:
          imageName: "dotnet-aspnet"
        sdk:
          imageName: "dotnet-sdk"
    steps:
      - template: .azure/build.yml
        parameters:
          command: buildAndPush
