# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  batch: true
  branches:
    include:
      - "master"
pr:
  autoCancel: true
  branches:
    include:
      - "*"

resources:
  - repo: self

pool:
  vmImage: "ubuntu-latest"

variables:
  DOCKER_BUILDKIT: 1
  CI: true

jobs:
  - job: Build
    displayName: Build
    strategy:
      matrix:
        dotnet-aspnet:
          imageName: "dotnet-aspnet"
        dotnet-sdk:
          imageName: "dotnet-sdk"
    steps:
      - template: .azure/build.yml
