apiVersion: mirror.plugin.fluxcd.io/v1beta1
kind: Config
artifacts:
  - source: docker.io/library/busybox
    destination: ghcr.io/visualon/library/busybox
    selector:
      semver: '>=1.36.1'
      regex:
        pattern: ^\d+\.\d+\.\d+$
      limit: 5
    includeReferrers: true
    overwrite: true
  - source: docker.io/library/mariadb
    destination: ghcr.io/visualon/library/mariadb
    selector:
      semver: '>=12.2.2'
      regex:
        pattern: ^\d+\.\d+\.\d+$
      limit: 5
    includeReferrers: true
    overwrite: true
  - source: docker.io/library/phpmyadmin
    destination: ghcr.io/visualon/library/phpmyadmin
    selector:
      semver: '>=5.2.3'
      regex:
        pattern: ^\d+\.\d+\.\d+$
      limit: 5
    includeReferrers: true
    overwrite: true
hosts:
  - host: ghcr.io
    username: ${GITHUB_REPOSITORY_OWNER} # ignored by GHCR; any value works
    credential:
      value: ${GH_TOKEN}
