apiVersion: mirror.plugin.fluxcd.io/v1beta1
kind: Config
artifacts:
  - source: public.ecr.aws/docker/library/mariadb
    destination: ghcr.io/visualon/library/mariadb
    selector:
      semver: '>=12.2.2'
      regex:
        pattern: ^\\d+\\.\\d+\\.\\d+$
      limit: 3
    includeReferrers: true
