FROM mcr.microsoft.com/dotnet/core/sdk:2.2.402-alpine@sha256:82478fabf603ee8fe171022712168940c3e6760b2013314c3e1b363abb53cdaf

RUN apk --update add git && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*
