FROM mcr.microsoft.com/dotnet/core/sdk:3.1.401-alpine@sha256:ff1134219afca5bd95fc16981089c66761e8ece405a44d122dcbbd73c10e5983

RUN apk --update add git && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*
