FROM mcr.microsoft.com/dotnet/core/sdk:2.2.402-alpine@sha256:dbbefe8005b9da31c22cbf94fe2832631d863eaa33bae92d8f8b8d244c226369

RUN apk --update add git && \
    rm -rf /var/lib/apt/lists/* && \
    rm /var/cache/apk/*
