FROM proget.inedo.com/productimages/inedo/proget:5.3.26@sha256:5889d85908ac12085715d3de894aedb8f3be4d053f3b4acf90b8f34abce21e06

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="proget" \
    org.opencontainers.image.source="https://my.inedo.com/proget/versions" \
    org.opencontainers.image.url="https://inedo.com/proget"