FROM proget.inedo.com/productimages/inedo/proget:5.3.21@sha256:ac5d0c9bc0cbd155e801e1aa830bd99ee27a32389538eb5e4db4bb497169753f

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="proget" \
    org.opencontainers.image.source="https://my.inedo.com/proget/versions" \
    org.opencontainers.image.url="https://inedo.com/proget"