FROM proget.inedo.com/productimages/inedo/proget:5.3.23@sha256:0e4b01680b9e54042a49fc3a15eb1c98f7518124337cc6a141282c9219a9ae51

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="proget" \
    org.opencontainers.image.source="https://my.inedo.com/proget/versions" \
    org.opencontainers.image.url="https://inedo.com/proget"