parameters:
  command: 'build'

steps:
  - task: Docker@2
    displayName: Build image
    inputs:
      command: ${{ parameters.command }}
      dockerfile: "$(Build.SourcesDirectory)/docker/$(imageName)/Dockerfile"
      buildContext: "$(Build.SourcesDirectory)/docker/$(imageName)"
      repository: "visualon/images"
      tags: |
        $(imageName)
