steps:
  - task: Docker@2
    displayName: Build image
    inputs:
      command: build
      dockerfile: "$(Build.SourcesDirectory)/docker/$(imageName)/Dockerfile"
      buildContext: "$(Build.SourcesDirectory)/docker/$(imageName)"
      repository: "$(imageName)"
      tags: "latest"
