FROM meltwater/drone-cache:v1.1.0@sha256:b52a859bebdb55d14b85cd966ffcca1c86353ade93ce58603fc7d0c3ea233026

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    org.opencontainers.image.authors="Michael Kriese <michael.kriese@visualon.de>" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.source="https://github.com/VisualOn/docker-images" \
    org.opencontainers.image.url="https://github.com/VisualOn/docker-images"
