FROM gitlab/gitlab-ce:13.3.4-ce.0@sha256:4e3c498f50e10fb60d787687bb74e445b2a583650333035955437146cc221462

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="gitlab-ce" \
    org.opencontainers.image.source="https://gitlab.com/gitlab-org/omnibus-gitlab" \
    org.opencontainers.image.url="https://gitlab.com/gitlab-org/gitlab"