FROM gitlab/gitlab-ce:13.6.1-ce.0@sha256:0fc33960add09c3a7e1ef672747930a865552c4b3577283f731a2ce5d31ee2c4

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="gitlab-ce" \
    org.opencontainers.image.source="https://gitlab.com/gitlab-org/omnibus-gitlab" \
    org.opencontainers.image.url="https://gitlab.com/gitlab-org/gitlab"