FROM gitlab/gitlab-ce:13.2.4-ce.0@sha256:33997b0e6d5b101d6f89df0dc810b9e90de14f188742cc9156ce463b974eeb58

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="gitlab-ce" \
    org.opencontainers.image.source="https://gitlab.com/gitlab-org/omnibus-gitlab" \
    org.opencontainers.image.url="https://gitlab.com/gitlab-org/gitlab"