FROM gitlab/gitlab-runner:alpine-v13.6.0@sha256:d559c9238de9a32ee00452993cc6bfdadccd9ec08ddabe15a91aa82cee9a32bb

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="gitlab-runner" \
    org.opencontainers.image.source="https://gitlab.com/gitlab-org/gitlab-runner" \
    org.opencontainers.image.url="https://gitlab.com/gitlab-org/gitlab-runner"