FROM gitlab/gitlab-runner:alpine-v13.1.0@sha256:a5b335f0ec72c7e2783c761bb52ae87b172818d95956b6c7d51ebb75c2886f7f

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="gitlab-runner" \
    org.opencontainers.image.source="https://gitlab.com/gitlab-org/gitlab-runner" \
    org.opencontainers.image.url="https://gitlab.com/gitlab-org/gitlab-runner"