FROM gitlab/gitlab-runner:alpine-v13.2.2@sha256:2d9a6f6b497169a5e87dfdd45e307ef916aa8333cfd27d2874280ed07b7df029

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="gitlab-runner" \
    org.opencontainers.image.source="https://gitlab.com/gitlab-org/gitlab-runner" \
    org.opencontainers.image.url="https://gitlab.com/gitlab-org/gitlab-runner"