FROM gitlab/gitlab-runner:alpine-v14.3.1@sha256:8bf563b4803cafbb1cf9da5b5513ea9e3956ec18e34b2fabdf60072b217b3c24

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="gitlab-runner" \
    org.opencontainers.image.source="https://gitlab.com/gitlab-org/gitlab-runner" \
    org.opencontainers.image.url="https://gitlab.com/gitlab-org/gitlab-runner"