FROM gitlab/gitlab-runner:alpine-v14.3.0@sha256:2a10c609c92df9038392ebc08413b6f90d7d986f65f69fac3bb437761e818137

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="gitlab-runner" \
    org.opencontainers.image.source="https://gitlab.com/gitlab-org/gitlab-runner" \
    org.opencontainers.image.url="https://gitlab.com/gitlab-org/gitlab-runner"