FROM gitlab/gitlab-runner:alpine-v14.8.2@sha256:3712d3e3548017056758516c5cb40fc0531f22d9b01bbfba502ab5356990cfd0

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="gitlab-runner" \
    org.opencontainers.image.source="https://gitlab.com/gitlab-org/gitlab-runner" \
    org.opencontainers.image.url="https://gitlab.com/gitlab-org/gitlab-runner"