FROM proget.inedo.com/productimages/inedo/proget:5.3.10@sha256:354b1ff4605c8176c1842b80c410a793abb1ec2450f2afc49fe767f4d5a3dbf8

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="proget" \
    org.opencontainers.image.source="https://my.inedo.com/proget/versions" \
    org.opencontainers.image.url="https://inedo.com/proget"