FROM proget.inedo.com/productimages/inedo/proget:5.3.20@sha256:b72c2833b28745c94f7060a123bedc99c0eb3e35b78d711515ff02f74348c9e5

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="proget" \
    org.opencontainers.image.source="https://my.inedo.com/proget/versions" \
    org.opencontainers.image.url="https://inedo.com/proget"