FROM proget.inedo.com/productimages/inedo/proget:5.3.17@sha256:1cea39c62fe416247bfa672b46b5e203e53109a6672668960aabd351f0f36e15

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="proget" \
    org.opencontainers.image.source="https://my.inedo.com/proget/versions" \
    org.opencontainers.image.url="https://inedo.com/proget"