FROM traefik:v3.7.6@sha256:21a3d83696379bac6434bb32e1dde0aff0e84ef2abd053ed3db87d3f45e749b2

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="traefik" \
    org.opencontainers.image.source="https://github.com/traefik/traefik" \
    org.opencontainers.image.url="https://traefik.io"
