FROM traefik:v3.5.1@sha256:c56901603318ee375477ee5c3f50d175d3ec42dc102efc2f1158f0756ba4dffa

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="traefik" \
    org.opencontainers.image.source="https://github.com/traefik/traefik" \
    org.opencontainers.image.url="https://traefik.io"
