FROM traefik:v3.7.8@sha256:5cb000ad823bfcfff911e22a4c4fa09cee74c7a2d960c012a1a46a8d0a159fcf

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="traefik" \
    org.opencontainers.image.source="https://github.com/traefik/traefik" \
    org.opencontainers.image.url="https://traefik.io"
