FROM gitlab/gitlab-ce:15.1.0-ce.0@sha256:66da8d58791cd55d0cb4b6bca80fd3d4c87780dd0b3af71fc3cf0c0d9e7011ad

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="gitlab-ce" \
    org.opencontainers.image.source="https://gitlab.com/gitlab-org/gitlab-foss" \
    org.opencontainers.image.url="https://gitlab.com/gitlab-org/gitlab-foss"
