FROM gitlab/gitlab-ce:14.8.4-ce.0@sha256:09a4581df9c8e093bf55527a52e47c8c2f4441ae54cb6ca39eb8f3c5ab79839d

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="gitlab-ce" \
    org.opencontainers.image.source="https://gitlab.com/gitlab-org/gitlab-foss" \
    org.opencontainers.image.url="https://gitlab.com/gitlab-org/gitlab-foss"
