FROM gitlab/gitlab-ce:13.8.1-ce.0@sha256:3e5e6d4388d6f1558f06979b0cbf41ae21dedbb870fc25f4186fc4a8cd1bdf26

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="gitlab-ce" \
    org.opencontainers.image.source="https://gitlab.com/gitlab-org/omnibus-gitlab" \
    org.opencontainers.image.url="https://gitlab.com/gitlab-org/gitlab"