FROM docker:27.3.1-dind@sha256:8d5039800a368057d99fc0a75167d80f345ac8650850509adc7fe25c64cba9dd

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="docker" \
    org.opencontainers.image.source="https://github.com/moby/moby" \
    org.opencontainers.image.url="https://mobyproject.org"
