FROM docker:27.5.1-dind@sha256:aa3df78ecf320f5fafdce71c659f1629e96e9de0968305fe1de670e0ca9176ce

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="docker" \
    org.opencontainers.image.source="https://github.com/moby/moby" \
    org.opencontainers.image.url="https://mobyproject.org"
