FROM docker:26.1.4-dind@sha256:dd43b430341a40d88f4f30edb03865daa9d6fa39c9b1da70f27e2a89cec3eae1

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="docker" \
    org.opencontainers.image.source="https://github.com/moby/moby" \
    org.opencontainers.image.url="https://mobyproject.org"
