FROM louislam/uptime-kuma:2.5.3@sha256:3e24e96c89efff0e3a4b0698cbdd36c15ad3022371db57166e5588853002ee5c

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="uptime-kuma" \
    org.opencontainers.image.source="https://github.com/louislam/uptime-kuma" \
    org.opencontainers.image.url="https://uptime.kuma.pet"
