FROM louislam/uptime-kuma:1.23.16@sha256:431fee3be822b04861cf0e35daf4beef6b7cb37391c5f26c3ad6e12ce280fe18

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="uptime-kuma" \
    org.opencontainers.image.source="https://github.com/louislam/uptime-kuma" \
    org.opencontainers.image.url="https://uptime.kuma.pet"
