FROM louislam/uptime-kuma:2.3.0@sha256:a8e5e69ce185d5425fcbf2ab14ddf808df5651fb2747a46a17cecf8ed5fd1af2

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="uptime-kuma" \
    org.opencontainers.image.source="https://github.com/louislam/uptime-kuma" \
    org.opencontainers.image.url="https://uptime.kuma.pet"
