FROM renovate/renovate:32.194.4-slim@sha256:8b906a82cc7a5b34f26b10586da05310d5b4b9fbf7264af47b78d116139c3942

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>"

# renovate: datasource=npm
RUN install-tool corepack 0.14.0
