FROM renovate/renovate:32.200.0-slim@sha256:29b7dbbdd9be22466b779629c452f232a319a3edf2ff784e348bee00a1e93855

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>"

# renovate: datasource=npm
RUN install-tool corepack 0.14.1
