name: Release

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

env:
  PLATFORM: linux/amd64

jobs:
  test:
    name: Release test
    runs-on: ubuntu-latest

    timeout-minutes: 30

    strategy:
      matrix:
        file: [verdaccio, rancher-cli, node, gitlab-ce, gitlab-runner, kubectl, proget]

    env:
      FILE: ${{ matrix.file }}
      IMAGE: visualon/${{ matrix.file }}

    steps:
      - uses: actions/checkout@v2.3.3

      - name: docker-config
        uses: renovatebot/internal-tools@v1.1.14
        with:
          command: docker-config

      - name: Build the Docker image
        run: |
          docker buildx build \
            --platform ${PLATFORM} \
            --output "type=docker" \
            --cache-from ${IMAGE}:cache \
            --cache-from visualon/docker-caches:${FILE} \
            --tag ${IMAGE} \
            .
        working-directory: ./docker/${{ env.FILE }}

      - name: Test run
        run: docker-compose --file docker-compose.test.yml run sut
        working-directory: ./docker/${{ env.FILE }}

  push:
    name: Release push
    runs-on: ubuntu-latest

    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    timeout-minutes: 30

    strategy:
      matrix:
        file: [verdaccio, rancher-cli, node, gitlab-ce, gitlab-runner, kubectl, proget]

    env:
      FILE: ${{ matrix.file }}
      IMAGE: visualon/${{ matrix.file }}

    steps:
      - uses: actions/checkout@v2.3.3

      - name: docker-config
        uses: renovatebot/internal-tools@v1.1.14
        with:
          command: docker-config

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_KEY }}" | docker login -u ${{ secrets.DOCKER_HUB_USER }} --password-stdin

      - name: Build the Docker image
        run: |
          docker buildx build \
            --platform ${PLATFORM} \
            --output "type=docker" \
            --cache-from ${IMAGE}:cache \
            --cache-from visualon/docker-caches:${FILE} \
            --cache-to visualon/docker-caches:${FILE} \
            --tag ${IMAGE} \
            .
        working-directory: ./docker/${{ env.FILE }}

      - name: Publish the Docker image
        run: |
          if [ -f push.sh ]; then
            chmod +x ./push.sh
            ./push.sh
          fi
        working-directory: ./docker/${{ env.FILE }}
